# Generated by Django 5.2.16 on 2026-07-30 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('query', models.JSONField(default=dict)),
                ('jobs_found', models.PositiveIntegerField(default=0)),
                ('jobs_new', models.PositiveIntegerField(default=0)),
                ('duplicates_marked', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('source_job_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('remote', models.BooleanField(null=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000)),
                ('apply_url', models.URLField(blank=True, max_length=1000)),
                ('salary_text', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_reasons', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('scored_by', models.CharField(blank=True, choices=[('rules', 'Rules'), ('llm', 'Llm')], max_length=10)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.searchrun')),
            ],
            options={
                'ordering': ['-score', '-posted_at'],
                'indexes': [models.Index(fields=['user', '-score'], name='jobs_job_user_id_09345a_idx'), models.Index(fields=['user', 'is_duplicate'], name='jobs_job_user_id_41fe85_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source', 'source_job_id'), name='unique_job_per_user_source')],
            },
        ),
        migrations.CreateModel(
            name='SourceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ok', 'Ok'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('search_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='jobs.searchrun')),
            ],
            options={
                'ordering': ['source_key'],
                'constraints': [models.UniqueConstraint(fields=('search_run', 'source_key'), name='unique_source_per_search')],
            },
        ),
    ]
